[package]
name = "arp-scanner"
version = "0.2.0"
authors = ["Gavyn Riebau <gavyn.riebau@gmail.com>"]
edition = "2018"

[dependencies]
pnet_datalink = "0.21.0"
ipnetwork = "0.12.0"
prettytable-rs = "0.8.0"
clap = "2.33.3"
pnet = "0.21.0"
